### ISSUE TITLE
使用webgl2上下文时粒子不显示

### ISSUE THREAD

**Issue by topo-go** [hongfaqiu/cesium-particle#12]
当在viewer中设置请求使用 webgl2 时，场景中不显示粒子了。

cesium 版本1.99，viewer 实例化传入以下参数。

`
  contextOptions: {
      requestWebGl2: true
   }
`

在 cesium 版本1.101 中是这样设置

`
 contextOptions: {
      requestWebgl1: false
    }
`

首先 calculateSpeed.frag 这个文件的第19行报错了，说是全局变量初始化必须是常量表达式

`float speedScaleFactor = speedFactor * pixelSize;`

将这句注释掉，然后写到对应方法里面去计算，重新打包后渲染不报错了，但是也看不到粒子了。

**Comment by hongfaqiu** [comment]
您好，我已经将代码升级到webgl2，现在支持最新版(1.103)了

**Comment by topo-go** [comment]
> 您好，我已经将代码升级到webgl2，现在支持最新版(1.103)了

感谢！
