### ISSUE TITLE
早期版本（如0.7.0）是否存在Particle3D API中fields字段自定义无效的问题

### ISSUE THREAD

**Issue by Zhouqingxin** [hongfaqiu/cesium-particle#13]
我尝试用这段代码加载一个字段为u, v, x, y的nc文件，但仍会出现这样的报错信息：‘error NetCDF file no such attribute: U
 all variables are: x,y,depth,u,v,ocean_time’，Particle3D API中fields的设置似乎并没有生效
```
particle3D = new Particle3D(viewer, {
  input: file,
  fields: {
    U: 'u',
    V: 'v',
    lon: 'x',
    lat: 'y'
  },
  colorTable,
  userInput
});
```

**Comment by hongfaqiu** [comment]
Yes, it's my fault, see this [commit ](https://github.com/hongfaqiu/cesium-particle/commit/989d86b66aab13e3e13e0a60bfb230e8c9f0433b#diff-22588e5ae864e50932943d436f6cb517f6be271844625a730ded07f74fb5e3baR65-R68)
