### ISSUE TITLE
添加EllipsoidSurfaceAppearance以后发现，粒子被盖住了，您知道需要怎么设置吗？是不是要改opengl代码？

### ISSUE THREAD

**Issue by YYunFeng** [hongfaqiu/cesium-particle#5]

**Comment by hongfaqiu** [comment]
您好，被盖住指的是部分被遮挡了吗？可以试试调整粒子系统的高度参数（particleHeight），避免被贴地的几何遮挡。
除此之外，粒子系统开启了[地形深度检测](https://github.com/hongfaqiu/cesium-particle/blob/40281db315e2feb522e08416e89ba74f3e1ec49c/packages/shader/glsl/screenDraw.frag#L14)，如果不需要这个功能，可以将这一行去掉。

**Comment by YYunFeng** [comment]
- 这是我自定义primitive时webgl渲染的alpha设置1的效果：
![image](https://user-images.githubusercontent.com/3302276/137709410-1fc2ddac-d2cf-4fda-939a-51cbdf05a5bd.png)
- 粒子并不会在上面显示，但是我通过entitie添加的经纬度线条却能显示在我自定义的primitive层级上面，并且我的粒子能在经纬度线条上看到粒子，如下图：
![image](https://user-images.githubusercontent.com/3302276/137709823-9411ebdb-df08-4322-a11c-d47173299f3c.png)
- 另外我把我自定义primitive时webgl渲染的alpha调透明一些，其实粒子就能看到如下图：
![image](https://user-images.githubusercontent.com/3302276/137708201-af21e9ba-a094-47e7-98aa-58aef98c1ffa.png)
- 我从cesium.js官方文档上并没找到primitive的设置层级关系，按我的理解，如果我自定义的primitive把粒子盖住了的话，那么我不应该在我的经纬度线条上看到粒子，所以不知道您知道不知道问题所在？

**Comment by hongfaqiu** [comment]
应该是深度测试的原因，粒子系统中手动写入了深度纹理，仅对地形进行了深度测试，还在找方法获取当前场景中纳入了新添加primitive图元后的深度纹理。

**Comment by hongfaqiu** [comment]
这个问题很难解决，至少不在我当前能力的范围内，从cesium社区中，我找到了相关的[问答](https://community.cesium.com/t/postprocessing-with-normal-and-depth-information/2850/4)。
这里有一个针对您的情况的解决方法：创建图元时，在PerInstanceColorAppearance配置项中，将translucent改为false。
——————
非常感谢您的提问，后续在工作之余，我还会继续尝试解决。
